### ISSUE TITLE
Enhance error messages

### ISSUE THREAD

**Issue by takahi-i** [recruit-tech/redpen#383]
Currently RedPen shows the stack when needed parameters are not specified. Following is a example as follows. I will make the message more human readable.

    19:30:07.125 [main] INFO  cc.redpen.ConfigurationLoader - Loading config from specified config file:     "/Users/ito/work/walter"
    Exception in thread "main" cc.redpen.RedPenException:  (No such file or directory)
        at cc.redpen.ConfigurationLoader.load(ConfigurationLoader.java:102)
        at cc.redpen.RedPen.<init>(RedPen.java:54)
        at cc.redpen.Main.run(Main.java:158)
        at cc.redpen.Main.main(Main.java:64)
    Caused by: java.io.FileNotFoundException:  (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at cc.redpen.ConfigurationLoader.load(ConfigurationLoader.java:99)
        ... 3 more

**Comment by takahi-i** [comment]
closed with #384
