### ISSUE TITLE
error appears when runs "export JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home'; /usr/local/bin/redpen --version"

### ISSUE THREAD

**Issue by griffin-stewie** [recruit-tech/redpen#399]
```
23:14:59,526 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/usr/local/Cellar/redpen/1.1.1/libexec/conf/logback.xml] at [file:/usr/local/Cellar/redpen/1.1.1/libexec/conf/logback.xml]
23:14:59,593 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
23:14:59,601 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
23:14:59,607 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDERR]
23:14:59,631 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
23:14:59,678 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
23:14:59,680 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
23:14:59,694 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
23:14:59,695 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/applog.%d{yyyy-MM}.log for the active file
23:14:59,700 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM' from file name pattern 'logs/applog.%d{yyyy-MM}.log'.
23:14:59,700 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Rollover at start of every month.
23:14:59,702 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sun Feb 15 23:14:59 JST 2015
23:14:59,704 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
23:14:59,704 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/applog.2015-02.log
23:14:59,705 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
23:14:59,706 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Failed to create parent directories for [/logs/applog.2015-02.log]
23:14:59,706 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(null,true) call failed. java.io.FileNotFoundException: logs/applog.2015-02.log (No such file or directory)
	at java.io.FileNotFoundException: logs/applog.2015-02.log (No such file or directory)
	at 	at java.io.FileOutputStream.open(Native Method)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:149)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at 	at cc.redpen.Main.<clinit>(Main.java:46)
23:14:59,706 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to INFO
23:14:59,706 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDERR] to Logger[ROOT]
23:14:59,707 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
23:14:59,707 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@649d209a - Registering current configuration as safe fallback point

1.1.1
```

This log is from Atom-RedPen's console.
Could you give me some advice to solve this issue ?

**Comment by takahi-i** [comment]
Can you please tell me the version of Atom redpen pacakge?

In my environment, redpen v1.1.1 installed with homebrew works with Atom redpen package (v0.2) works as expected.

**Comment by griffin-stewie** [comment]
my env is

- RedPen
    - v1.1.1
    - via homebrew
- text editor
    - atom editor
    - v0.179.0
- redpen atom package
    - v 0.2.0
- OS
    - OS X 10.10.2

**Comment by takahi-i** [comment]
Thank you for the information. I succeeded to reproduce the problem in my environment.  

    10:52:16,164 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(null,true) call failed. java.io.FileNotFoundException: logs/applog.2015-02.log (No such file or directory)
	at java.io.FileNotFoundException: logs/applog.2015-02.log (No such file or directory)
	at 	at java.io.FileOutputStream.open(Native Method)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:206)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:149)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)

**Comment by takahi-i** [comment]
I made a patch for this problem #402

**Comment by takahi-i** [comment]
I have uploaded the redpen package with the #402 patch. Can you please check if the package work in your atom repden package @griffin-stewie?

**Comment by griffin-stewie** [comment]
v1.1.2-experimental works great for me @takahi-i !

**Comment by takahi-i** [comment]
Excellent!
