### ISSUE TITLE
markdown parser crashed

### ISSUE THREAD

**Issue by griffin-stewie** [recruit-tech/redpen#403]
## happens

I used redpen on terminal and an error has occurred.

## error log

```
% redpen -c "redpen-conf-ja.xml" -r json -f markdown test.md

[2015-02-18 13:58:00.905][INFO ] cc.redpen.ConfigurationLoader - Loading config from specified config file: "/Users/zushi/Desktop/redpen-conf-ja.xml"
[2015-02-18 13:58:00.916][INFO ] cc.redpen.ConfigurationLoader - Succeeded to load configuration file
[2015-02-18 13:58:00.916][INFO ] cc.redpen.ConfigurationLoader - Language is set to "ja"
[2015-02-18 13:58:00.917][INFO ] cc.redpen.ConfigurationLoader - No "symbols" block found in the configuration
[2015-02-18 13:58:01.368][INFO ] cc.redpen.parser.SentenceExtractor - "[。, ？, ！]" are added as a end of sentence characters
[2015-02-18 13:58:01.368][INFO ] cc.redpen.parser.SentenceExtractor - "[’, ”]" are added as a right quotation characters
[2015-02-18 13:58:01.373][INFO ] cc.redpen.validator.Validator - max_len is set to 100
[2015-02-18 13:58:01.375][INFO ] cc.redpen.validator.sentence.KatakanaSpellCheckValidator - Loading default katakana word dictionary
[2015-02-18 13:58:01.376][INFO ] cc.redpen.validator.sentence.KatakanaSpellCheckValidator - Succeeded to load default dictionary.
[2015-02-18 13:58:01.379][INFO ] cc.redpen.validator.Validator - max_num is set to 1500
[2015-02-18 13:58:01.380][INFO ] cc.redpen.validator.Validator - max_num is not set. Use default value of 5
[2015-02-18 13:58:01.381][INFO ] cc.redpen.validator.sentence.DoubledWordValidator - Loading default doubled word skip list dictionary for "ja".
[2015-02-18 13:58:01.381][INFO ] cc.redpen.validator.sentence.DoubledWordValidator - Succeeded to load default dictionary.
[2015-02-18 13:58:01.383][INFO ] cc.redpen.validator.Validator - max_num is not set. Use default value of 3

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 17, Size: 17
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at cc.redpen.parser.markdown.MergedCandidateSentence.getRangedLinks(MergedCandidateSentence.java:65)
at cc.redpen.parser.markdown.ToFileContentSerializer.extractSentences(ToFileContentSerializer.java:174)
at cc.redpen.parser.markdown.ToFileContentSerializer.lambda$createSentenceList$5(ToFileContentSerializer.java:148)
at cc.redpen.parser.markdown.ToFileContentSerializer$$Lambda$7/2120063568.accept(Unknown Source)
at java.util.Optional.ifPresent(Optional.java:159)
at cc.redpen.parser.markdown.ToFileContentSerializer.createSentenceList(ToFileContentSerializer.java:147)
at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:302)
at org.pegdown.ast.ListItemNode.accept(ListItemNode.java:29)
at cc.redpen.parser.markdown.ToFileContentSerializer.visitChildren(ToFileContentSerializer.java:72)
at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:282)
at org.pegdown.ast.BulletListNode.accept(BulletListNode.java:29)
at cc.redpen.parser.markdown.ToFileContentSerializer.visitChildren(ToFileContentSerializer.java:72)
at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:327)
at org.pegdown.ast.RootNode.accept(RootNode.java:51)
at cc.redpen.parser.markdown.ToFileContentSerializer.toFileContent(ToFileContentSerializer.java:88)
at cc.redpen.parser.MarkdownParser.parse(MarkdownParser.java:90)
at cc.redpen.parser.BaseDocumentParser.parse(BaseDocumentParser.java:47)
at cc.redpen.RedPen.parse(RedPen.java:120)
at cc.redpen.Main.run(Main.java:174)
at cc.redpen.Main.main(Main.java:65)
```

## markdown file

```markdown
* [Pandoc](http://johnmacfarlane.net/pandoc/ "Pandoc - About pandoc") を使って PDF 化
```

## conf file

```xml
<redpen-conf lang="ja">
    <validators>
        <validator name="SentenceLength">
            <property name="max_len" value="100"/>
        </validator>
        <validator name="InvalidSymbol"/>
        <validator name="KatakanaEndHyphen"/>
        <validator name="KatakanaSpellCheck"/>
        <validator name="SectionLength">
            <property name="max_num" value="1500"/>
        </validator>
        <validator name="ParagraphNumber"/>
        <validator name="DoubledWord" />
        <validator name="SpaceBetweenAlphabeticalWord" />
        <validator name="CommaNumber" />
        <validator name="SuccessiveWord" />
    </validators>
</redpen-conf>
```

## my env

- RedPen
    - v1.1.1
    - via homebrew
- OS
    - OS X 10.10.2

**Comment by takahi-i** [comment]
Thank you a lot for the report @griffin-stewie!  I will look into the problem.

**Comment by takahi-i** [comment]
I added a tiny fix for the crash and enhanced the log messages. Can you please a new redpen package?  https://github.com/recruit-tech/redpen/releases/tag/v1.1.2-experimental-2

**Comment by griffin-stewie** [comment]
:+1: 
It works!
Thank you @takahi-i

**Comment by takahi-i** [comment]
Great!
